### PR TITLE
Ignore MIDI events when the browser tab isn't active

### PR DESCRIPTION
**Pull request by samuelmaddock**
Includes changes for #3. These changes are untested until I can get the app running locally. Let me know if you just want to test them yourself though.

### CODE REVIEW

**Comment by samuelmaddock** [comment]
I tested by making the changes in Chrome DevTools on the live site 😛, seems to work as intended.

**Comment by leafo** [comment]
what happens if you press a note, switch windows, release note, then come back? :)

**Comment by samuelmaddock** [comment]
@leafo Good catch, I've committed a fix.

**Comment by samuelmaddock** [comment]
This works, however, it attempts to call `releaseNote()` which then checks if the note is held.

**Comment by leafo** [comment]
I think this is fine, release note should be a noop if the note isn't already held

**Pull request merged**
